modLoader = "javafml" #mandatory
loaderVersion = "${fgloaderrange}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "$modlicense"

[[mods]] #mandatory
    modId="${modid}"
    version="${modversion}"
    displayName="${modname}"
    logoFile="icon.png" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-threads" #optional
    authors="${modauthor}" #optional
    credits="${modcredits}" #optional
    description = '''${mod_description}'''

[[mixins]]
    config="$modid.$mixin_file_suffix"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.${modid}]] #optional
    modId = "neoforge"
    type="required"
    versionRange="${fgrange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modid}]]
    modId = "minecraft"
    type="required"
    versionRange="${mcrange}"
    ordering = "NONE"
    side = "BOTH"